### ISSUE TITLE
Do you consider opensourcing Service Point Picker JS lib?

### ISSUE THREAD

**Issue by Pyo25** [SendCloud/spp-integration-example#12] opened 2020-06-04 21:48 UTC
Hi @erickwilder ,

Considering the fact that:

- there are a few open issues without answer nor follow-up (and possibly some bugs)
- the JS lib hasn't changed since 3 years now (according [to this page](https://support.sendcloud.com/hc/en-us/articles/360024967612-Service-points-for-API-Integrations)
- there are several enhancements that can be done on this lib

Would Sendcloud team consider open-sourcing the lib?

I'm CTO of a belgian e-shop, client of Sendcloud since a few years now. Our team would be happy to contribute!

Cheers

**Comment by erickwilder** [comment] 2020-06-05 04:56
Hello @Pyo25 

The information in the support page is not accurate. The library is maintained internally and it did receive some updates in the past months.

The issue here is one of visibility; neither the version in the URL did follow any strict versioning when updates came out nor a changelog is publicly available.

About open sourcing it I'll check with the rest of the team on a good strategy for it.

**Comment by Pyo25** [comment] 2020-06-08 12:51
Hi @erickwilder ,

Thank you for your quick answer.

Side question: how can we be notified of new releases then? 
Github Releases could help here (but then the lib has to be open-sourced 😉)

Cheers

**Comment by erickwilder** [comment] 2020-06-08 18:46
I think I can keep a public changelog (for now) before we decide about opening it to the public.

**Comment by philipp-rudloff-sendcloud** [comment] 2021-10-01 09:45
We’re actively maintaining the current service point picker solution and have fixed several issues in the past months in particular. We’re also starting active feature development for the picker again. That being said, there are no plans to open source the service point picker core script or any of the associated scripts.

I do agree that we should have a publicly available release log for service point/checkout features. I’ve filed an internal ticket for considering this. We’re not using this GitHub repository (or any repository associated to the Sendcloud GitHub organization) for bug reporting and feature requests so I’m closing this issue for now. The issue is referenced in the aforementioned ticket I filed and so the issue should be updated if/once there is any notable movement on it.

**Closed by philipp-rudloff-sendcloud** 2021-10-01 09:45 UTC
Labels: question
